var assert = require('assert');
var es = require('event-stream');
var File = require('vinyl');
var coffee2closure = require('./index');

describe('gulp-coffee2closure', function() {
  describe('in buffer mode', function() {

    it('should prepend text', function(done) {

      var fakeFile = new File({
        contents: new Buffer('function Person() {};')
      });

      var c2c = coffee2closure();

      c2c.write(fakeFile);

      c2c.once('data', function(file) {
        assert(file.isBuffer());

        contents = file.contents.toString('utf8');
        assert.ok(contents.indexOf(
          '// Generated by github.com/steida/coffee2closure') != -1);
        done();
      });

    });

  });
});
